#!/bin/bash
set -x
# set -o xtrace

if [ -e "$(dirname $0)/common.sh" ]; then
    source "$(dirname $0)/common.sh"
elif [ -e "$(dirname $0)/../common/common.sh" ]; then
   source "$(dirname $0)/../common/common.sh"
fi

log_info "$0 $*"

init()
{
   log_info "hardcoded:build:id:42"
   print_success
}

create()
{
   print_success
}

delete()
{
   print_success purged
}

attach()
{
   print_not_supported
}

detach()
{
   print_not_supported
}

mountdest()
{
   print_success
}

unmount()
{
   print_success
}

# Every script must call main as such
main "$@"
