#!/bin/bash
set -x
set -o xtrace

if [ -e "$(dirname $0)/common.sh" ]; then
    source $(dirname $0)/common.sh
elif [ -e "$(dirname $0)/../common/common.sh" ]; then
    source $(dirname $0)/../common/common.sh
fi

init()
{
    logger "$@"
    print_success
}

create()
{
    logger "$@"
    docker volume create --driver=vsphere --name=rancher-vsphere-test -o diskformat=zeroedthick -o size=1gb
    print_success
}

delete()
{
    logger "$@"
    docker volume rm rancher-vsphere-test
    print_success
}

attach()
{
    logger "$@"
    # print_not_supported
#    # The OPTS variable will be populated from the input JSON as a map of key/values
#    IMG=${OPTS[volumeID]}.img
#    if [ ! -e "${IMG}" ]; then
#        print_error "Failed to find ${IMG}"
#    fi
#
#    DEVICE=$(get_attached_dev ${IMG})
#    if [ $? -ne 0 ]
#    then
#        DEVICE=$(losetup --show -f ${IMG})
#    fi
#
   print_device "hest"
}

detach()
{
    logger "$@"
    # ${DEVICE} will be set with the device that should be detached
    # losetup -d ${DEVICE}
    print_not_supported
}

mountdest()
{
    logger "$@"
    # ${MNT_DEST} will be set with the directory where the filesystem should be mounted
    # ${DEVICE} will be the device returned from attach, if any
    # ${OPTS} will be populated with the options from the JSON input
    print_not_supported
}

unmount()
{
    logger "$@"
    # ${MNT_DEST} will be set with the directory from which the filesystem should be unmounted
    print_not_supported
}

# Every script must call main as such
main "$@"
